Repository pyccel/psydac, pull requests merged in 2024-03, with the labels that each got.

#384 Speed up Pyccelization of built-in kernels
  psydac/core/field_evaluation_kernels.py
  psydac/linalg/kernels/axpy_kernels.py
  psydac/linalg/kernels/inner_kernels.py
  psydac/linalg/kernels/matvec_kernels.py
  psydac/linalg/kernels/stencil2coo_kernels.py
  psydac/linalg/kernels/transpose_kernels.py
  psydac_accelerate.py
  pyproject.toml
Labels: performance, package

#378 Improve developers' documentation
  .github/workflows/documentation.yml
  docs/source/conf.py
  docs/source/index.rst
  docs/source/maintenance.rst
  docs_requirements.txt
  psydac/linalg/basic.py
Labels: documentation

#393 Fix `None` value in `Pushforward`
  psydac/feec/pushforward.py
  psydac/feec/tests/test_pushforward.py
  psydac/linalg/tests/test_stencil_matrix.py
Labels: bug

#392 Fix several errors in `cell_index_p`
  psydac/core/bsplines.py
  psydac/core/bsplines_kernels.py
  psydac/core/tests/test_bsplines_kernel.py
Labels: bug
